### ISSUE TITLE
Work Checklist

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/DSCI_532_L02_group207_dashboards#43]
- [x] PEP8 Code Refactoring

- [x] Restructure the directories (i.e. return it back to how we had it originally)

- [x] Update Teamwork Contract

- [x] Make new repository for Milestone 3

- [x] Reflections (see Milestone 3)

- [x] Feedback:
- Change size of labels
- Change title of map to include the actual state
- Add header to the top of the app to actually explain what the app does and its intended purpose, along with the data it uses
- Add an instruction explaining how the map actually works

**Comment by braydentang1** [comment]
All of these issues have been addressed!
